In [2]:
import numpy as np

Angka tunggal adalah 0 dimensi, kalau angka2 tunggal digabung2kan jadi 1 dimensi

In [3]:
mylist = [1,2,3,4,5]
myarray = np.array(mylist)
myarray

array([1, 2, 3, 4, 5])

1 DIMENSI adalah kumpulan 0 dimensi yang ada banyakm hanya 1 list (list = [])

In [4]:
arr_1d = np.array([1,2,3,4,5])
type(arr_1d)

numpy.ndarray

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d.ndim) #cek dimensi
print(arr_1d.shape)  #cek shape array (baris dan kolomnya)

1
(5,)


2 DIMENSI adalah kumpulan dari 1 dimensi yang ada banyak. (gabungan beberapa list di dalam list -> list = [ [...], [...] ])

In [ ]:
mylist = ([1,2,3,4,5], [7,8,9,10,11], [12,13,14,15,16])
arr_2d = np.array(mylist)
print(arr_2d)

print(arr_2d.ndim)
print(arr_2d.shape)  # -> outputnya 3 baris 5 kolom (3,5)


[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
2
(3, 5)


3 DIMENSI adalah kumpulan dari 2 dimensi yang ada banyak -> list = [ [[...], [...]] , [[...], [...]] ]

In [ ]:
mylist = ([[1,2,3,4,5], [7,8,9,10,11], [12,13,14,15,16]],
          [[1,2,3,4,5], [7,8,9,10,11], [12,13,14,15,16]])
arr_3d = np.array(mylist)

print(arr_3d)

print(arr_3d.ndim)
print(arr_3d.shape)  # -> outputnya 2 matix 3 baris dengan isi data masing2 5 kolom (2,3,5)

[[[ 1  2  3  4  5]
  [ 7  8  9 10 11]
  [12 13 14 15 16]]

 [[ 1  2  3  4  5]
  [ 7  8  9 10 11]
  [12 13 14 15 16]]]
3
(2, 3, 5)


RESHAPE

In [22]:
mylist = [ 
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
]

arr_3d = np.array(mylist)

# SYARAT RESHAPE = hasil kali baris, kolom dan isi tetap sama

# hasil kali = 5*3*4 = 60
print(arr_3d.reshape(12,5))

print("---------------------------- INI KEBALIKANNYA ----------------------------")

print(arr_3d.reshape(5,12))

[[1 2 3 4 1]
 [2 3 4 1 2]
 [3 4 1 2 3]
 [4 1 2 3 4]
 [1 2 3 4 1]
 [2 3 4 1 2]
 [3 4 1 2 3]
 [4 1 2 3 4]
 [1 2 3 4 1]
 [2 3 4 1 2]
 [3 4 1 2 3]
 [4 1 2 3 4]]
---------------------------- INI KEBALIKANNYA ----------------------------
[[1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]]


In [ ]:
# SIZE = jumlah membernya

mylist = [ 
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
    [[1,2,3,4], [1,2,3,4], [1,2,3,4]],
]

arr_3d = np.array(mylist)
arr_3d.size 

60

SOAL LATIHAN BASIC

In [24]:
#soal 1

mylist = [[1,2,3], [4,5,6]], [[4,5,6], [7,8,9]], [[7,8,9], [1,2,3]]
arr_3d = np.array(mylist)
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]]]
3
(3, 2, 3)


In [36]:
#soal 2
mylist = [[1,2,3], [4,5,6]], [[4,5,6], [7,8,9]], [[7,8,9], [1,2,3]]
arr_3d = np.array(mylist)
print(arr_3d.reshape(6,1,3))



[[[1 2 3]]

 [[4 5 6]]

 [[4 5 6]]

 [[7 8 9]]

 [[7 8 9]]

 [[1 2 3]]]


In [30]:
#soal 3
mylist = [[1,2,3], [4,5,6]], [[4,5,6], [7,8,9]], [[7,8,9], [1,2,3]]
arr_3d = np.array(mylist)
print(arr_3d.reshape(3,2,3))

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]]]


In [31]:
#soal 4
mylist = [[1,2,3], [4,5,6]], [[4,5,6], [7,8,9]], [[7,8,9], [1,2,3]]
arr_3d = np.array(mylist)
print(arr_3d.reshape(3,6))

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]
 [7 8 9 1 2 3]]


ZEROES DAN ONES (membuat numpy yang bentuknya )

In [44]:
#1 dimensi
print(np.zeros(3))

print("--------------------")

print(np.ones(3))

print("--------------------")

print(np.zeros([3,4]))

print("--------------------")

print(np.ones([2,3,4]))


[0. 0. 0.]
--------------------
[1. 1. 1.]
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [45]:
np.empty([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

ARANGE (ARRAY RANGE) -> membuat range untuk array

In [ ]:
#versi biasa
for i in range (10):
    print(i)


#versi numpy
np.arange(0,10,2) #> range(start,stop,step)

0
1
2
3
4
5
6
7
8
9


array([0, 2, 4, 6, 8])

RANDOM

In [ ]:
# RAND(shape) -> hasilnya float
np.random.rand(2,3)  #> output setiap run-nya selalu baru/ganti

#kalau mau sekali saja random, terus di run ga berubah pakai random.seed() -> isi angkanya bebas tp hasilnya akan disimpan di kode tersebut
np.random.seed(42)  #> hasil random disimpan ke var42, kalau diganti nanti randomnya ganti, tp bisa dipanggil lagi
np.random.rand(2,3)


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [ ]:
# RANDN(shape) -> hasilnya float tapi ada angka negatif (-)
np.random.seed(42)
np.random.randn(2,3)  #> randn(baris,kolom)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [ ]:
# RANDINT(start, stop, shape) -> hasilnya integer
np.random.seed(42)
np.random.randint(0,11, size=(2,3))  #> randint(start, stop, size=(baris,kolom))

array([[ 6,  3, 10],
       [ 7,  4,  6]], dtype=int32)

MAX, MIN, ARGMAX, ARGMIN, INDEXING

In [ ]:
np.random.seed(42)
arr = np.random.randint(100,200, size=(2,3,4))
print(arr)

print(f'\nnilai min dari arr = {np.min(arr)}')
print(f'letak dari nilai min arr = {np.argmin(arr)}')
print(f'nilai max dari arr = {np.max(arr)}')
print(f'letak dari nilai max arr = {np.argmax(arr)}\n')

#INDEXING
print('matrix ke 1, baris ke 0, kolom ke 3 =',arr[1][0][3])  #> matrix ke 1, baris ke 0, kolom ke 3
print('matrix ke 1, baris ke 0, kolom ke 0 =',arr[1,0,0]) #> matrix ke 1, baris ke 0, kolom ke 0
print('matrix ke 1, baris ke 0, semua kolom =',arr[1,0,:]) #> matrix ke 1, baris ke 0, semua kolom
print('matrix ke 1, baris ke 1, semua kolom =',arr[1,1]) #> matrix ke 1, baris ke 1, semua kolom
print('semua matrix, semua baris, kolom ke 2 =',arr[:,:,2]) #> semua matrix, semua baris, kolom ke 2


[[[151 192 114 171]
  [160 120 182 186]
  [174 174 187 199]]

 [[123 102 121 152]
  [101 187 129 137]
  [101 163 159 120]]]

nilai min dari arr = 101
letak dari nilai min arr = 16
nilai max dari arr = 199
letak dari nilai max arr = 11

matrix ke 1, baris ke 0, kolom ke 3 = 152
matrix ke 1, baris ke 0, kolom ke 0 = 123
matrix ke 1, baris ke 0, semua kolom = [123 102 121 152]
matrix ke 1, baris ke 1, semua kolom = [101 187 129 137]
semua matrix, semua baris, kolom ke 2 = [[114 182 187]
 [121 129 159]]


FANCY INDEXING

In [ ]:
np.random.seed(42)
arr = np.random.randint(0,100, size=(10))

SOAL LATIHAN 

In [19]:
#NOMOR 1
np.random.seed(42)
arr = np.random.randint(0,100, size=(3,2,3))
print(arr)
print("\n------setelah diganti------\n")
arr[0,0,1] = 1
print(arr)

[[[51 92 14]
  [71 60 20]]

 [[82 86 74]
  [74 87 99]]

 [[23  2 21]
  [52  1 87]]]

------setelah diganti------

[[[51  1 14]
  [71 60 20]]

 [[82 86 74]
  [74 87 99]]

 [[23  2 21]
  [52  1 87]]]


In [ ]:
#NOMOR 2
np.random.seed(42)
arr = np.random.randint(0,100, size=(3,5,3))
print(arr[arr>10])

[51 92 14 71 60 20 82 86 74 74 87 99 23 21 52 87 29 37 63 59 20 32 75 57
 21 88 48 90 58 41 91 59 79 14 61 61 46 61 50 54 63]


In [21]:
#NOMOR 3
np.random.seed(42)
arr = np.random.randint(0,50, size=(3,5,3))
print(arr)
print("\n------setelah diganti------\n")
arr[arr<10] = 0
print(arr)

[[[38 28 14]
  [42  7 20]
  [38 18 22]
  [10 10 23]
  [35 39 23]]

 [[ 2 21  1]
  [23 43 29]
  [37  1 20]
  [32 11 21]
  [43 24 48]]

 [[26 41 27]
  [15 14 46]
  [43  2 36]
  [ 6 20  8]
  [38 17  3]]]

------setelah diganti------

[[[38 28 14]
  [42  0 20]
  [38 18 22]
  [10 10 23]
  [35 39 23]]

 [[ 0 21  0]
  [23 43 29]
  [37  0 20]
  [32 11 21]
  [43 24 48]]

 [[26 41 27]
  [15 14 46]
  [43  0 36]
  [ 0 20  0]
  [38 17  0]]]


In [ ]:
#NOMOR 4
np.random.seed(42)
arr1 = np.random.randint(0,20, size=(3,2))
arr2 = np.random.randint(0,20, size=(2,3))

print(arr1)
print(arr2)
print("---------------- GABUNG ----------------")
print(np.concatenate((arr1,arr2.T), axis=1))

[[ 6 19]
 [14 10]
 [ 7  6]]
[[18 10 10]
 [ 3  7  2]]
---------------- GABUNG ----------------
[[ 6 19 18  3]
 [14 10 10  7]
 [ 7  6 10  2]]


In [33]:
#NOMOR 5
A = np.array([[1,3],[2,5]])
V = np.array([1,3])

print(A*V)

[[ 1  9]
 [ 2 15]]


In [35]:
#NOMOR 6
A = np.array([[2,4,6,8],[1,3,5,7],[9,11,13,15]])
V = np.array([2,2,2,2])
print(A*V)

[[ 4  8 12 16]
 [ 2  6 10 14]
 [18 22 26 30]]
